import bcrypt from 'bcryptjs'
import {
  createId,
  createInviteCode,
  DEFAULT_HEALTH_TARGETS,
  DEFAULT_MEAL_PERIODS,
  daysAgoIso,
  getWeekDateKeys,
  nowIso,
  plusDaysIso,
  startOfWeek,
} from './utils.js'

const SEED_PASSWORD_HASH = bcrypt.hashSync('Password123!', 10)

export function createSeedData() {
  const weekStart = startOfWeek()
  const weekDates = getWeekDateKeys(weekStart)

  const users = [
    {
      id: 'u1',
      email: 'sarah@example.com',
      password: SEED_PASSWORD_HASH,
      displayName: 'Sarah Chen',
      avatarUrl: undefined,
      createdAt: daysAgoIso(120),
      currentHouseholdId: 'h1',
      healthTargets: {
        ...DEFAULT_HEALTH_TARGETS,
        calories: 2100,
        protein: 130,
      },
    },
    {
      id: 'u2',
      email: 'mike@example.com',
      password: SEED_PASSWORD_HASH,
      displayName: 'Mike Park',
      avatarUrl: undefined,
      createdAt: daysAgoIso(110),
      currentHouseholdId: 'h1',
      healthTargets: {
        ...DEFAULT_HEALTH_TARGETS,
        calories: 2400,
        protein: 150,
      },
    },
    {
      id: 'u3',
      email: 'emma@example.com',
      password: SEED_PASSWORD_HASH,
      displayName: 'Emma Park',
      avatarUrl: undefined,
      createdAt: daysAgoIso(95),
      currentHouseholdId: 'h1',
      healthTargets: {
        ...DEFAULT_HEALTH_TARGETS,
        calories: 1800,
        protein: 100,
      },
    },
  ]

  const households = [
    {
      id: 'h1',
      name: 'The Chen-Park Home',
      color: '#22c55e',
      avatarUrl: undefined,
      createdAt: daysAgoIso(120),
    },
  ]

  const householdMembers = [
    {
      id: 'm1',
      userId: 'u1',
      householdId: 'h1',
      displayName: 'Sarah Chen',
      avatarUrl: undefined,
      role: 'admin',
      joinedAt: daysAgoIso(120),
    },
    {
      id: 'm2',
      userId: 'u2',
      householdId: 'h1',
      displayName: 'Mike Park',
      avatarUrl: undefined,
      role: 'member',
      joinedAt: daysAgoIso(110),
    },
    {
      id: 'm3',
      userId: 'u3',
      householdId: 'h1',
      displayName: 'Emma Park',
      avatarUrl: undefined,
      role: 'member',
      joinedAt: daysAgoIso(95),
    },
  ]

  const invites = [
    {
      code: createInviteCode('Chen Park'),
      householdId: 'h1',
      expiresAt: plusDaysIso(7),
      createdBy: 'u1',
    },
  ]

  const householdPreferences = [
    {
      householdId: 'h1',
      dietaryPreferences: ['nut-free'],
      mealPeriods: [...DEFAULT_MEAL_PERIODS],
    },
  ]

  const recipes = [
    {
      id: 'r1',
      householdId: 'h1',
      title: 'Grilled Chicken Caesar Salad',
      description: 'A crisp Caesar salad with grilled chicken, shaved parmesan, and a bright creamy dressing.',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600&h=400&fit=crop',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      tags: ['healthy', 'salad', 'quick', 'high-protein'],
      ingredients: [
        { id: createId('ing'), quantity: 2, unit: 'lbs', name: 'chicken breast' },
        { id: createId('ing'), quantity: 1, unit: 'head', name: 'romaine lettuce' },
        { id: createId('ing'), quantity: 0.5, unit: 'cup', name: 'parmesan cheese, shaved' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'croutons' },
        { id: createId('ing'), quantity: 0.25, unit: 'cup', name: 'Caesar dressing' },
      ],
      instructions: [
        'Season the chicken with olive oil, salt, and pepper.',
        'Grill over medium-high heat until cooked through, then rest and slice.',
        'Toss the romaine with dressing in a large bowl.',
        'Top with sliced chicken, parmesan, and croutons.',
        'Serve immediately.',
      ],
      sourceUrl: undefined,
      createdBy: 'u1',
      createdAt: daysAgoIso(12),
      updatedAt: daysAgoIso(12),
    },
    {
      id: 'r2',
      householdId: 'h1',
      title: 'Creamy Pasta Carbonara',
      description: 'An easy carbonara with crispy pancetta, eggs, pecorino, and lots of black pepper.',
      imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&h=400&fit=crop',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      tags: ['italian', 'pasta', 'comfort-food', 'dinner'],
      ingredients: [
        { id: createId('ing'), quantity: 1, unit: 'lb', name: 'spaghetti' },
        { id: createId('ing'), quantity: 6, unit: 'oz', name: 'pancetta' },
        { id: createId('ing'), quantity: 4, unit: '', name: 'eggs' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'pecorino romano, grated' },
        { id: createId('ing'), quantity: 1, unit: 'tsp', name: 'black pepper' },
      ],
      instructions: [
        'Cook the spaghetti in well-salted water.',
        'Render the pancetta in a skillet until crisp.',
        'Whisk eggs, cheese, and pepper in a bowl.',
        'Toss the hot pasta with pancetta, then add the egg mixture off the heat.',
        'Loosen with pasta water until silky, then serve.',
      ],
      sourceUrl: undefined,
      createdBy: 'u2',
      createdAt: daysAgoIso(10),
      updatedAt: daysAgoIso(10),
    },
    {
      id: 'r3',
      householdId: 'h1',
      title: 'Thai Green Curry',
      description: 'Fragrant green curry with chicken, coconut milk, bamboo shoots, and Thai basil.',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      tags: ['thai', 'curry', 'spicy', 'dinner'],
      ingredients: [
        { id: createId('ing'), quantity: 1.5, unit: 'lbs', name: 'chicken thighs' },
        { id: createId('ing'), quantity: 3, unit: 'tbsp', name: 'green curry paste' },
        { id: createId('ing'), quantity: 1, unit: 'can', name: 'coconut milk' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'bamboo shoots' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'Thai basil leaves' },
      ],
      instructions: [
        'Cook the rice according to package directions.',
        'Fry the curry paste in a little coconut cream until fragrant.',
        'Add the chicken and cook until lightly browned.',
        'Pour in the remaining coconut milk and simmer with bamboo shoots.',
        'Finish with Thai basil and serve over rice.',
      ],
      sourceUrl: undefined,
      createdBy: 'u1',
      createdAt: daysAgoIso(8),
      updatedAt: daysAgoIso(8),
    },
    {
      id: 'r4',
      householdId: 'h1',
      title: 'Overnight Oats with Berries',
      description: 'No-cook overnight oats layered with berries, yogurt, honey, and vanilla.',
      imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&h=400&fit=crop',
      prepTime: 5,
      cookTime: 0,
      servings: 2,
      tags: ['breakfast', 'healthy', 'no-cook', 'meal-prep'],
      ingredients: [
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'rolled oats' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'milk' },
        { id: createId('ing'), quantity: 0.5, unit: 'cup', name: 'Greek yogurt' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'mixed berries' },
        { id: createId('ing'), quantity: 2, unit: 'tbsp', name: 'honey' },
      ],
      instructions: [
        'Stir together oats, milk, yogurt, and honey.',
        'Top with berries and refrigerate overnight.',
        'Serve chilled in the morning.',
      ],
      sourceUrl: undefined,
      createdBy: 'u3',
      createdAt: daysAgoIso(7),
      updatedAt: daysAgoIso(7),
    },
    {
      id: 'r5',
      householdId: 'h1',
      title: 'Black Bean Tacos',
      description: 'Fast vegetarian tacos with seasoned black beans, avocado, pico, and lime.',
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      tags: ['vegetarian', 'mexican', 'quick', 'dinner'],
      ingredients: [
        { id: createId('ing'), quantity: 2, unit: 'cans', name: 'black beans' },
        { id: createId('ing'), quantity: 8, unit: '', name: 'corn tortillas' },
        { id: createId('ing'), quantity: 2, unit: '', name: 'avocados' },
        { id: createId('ing'), quantity: 1, unit: 'cup', name: 'pico de gallo' },
        { id: createId('ing'), quantity: 2, unit: '', name: 'limes' },
      ],
      instructions: [
        'Warm the beans with cumin and chili powder.',
        'Heat the tortillas until soft and lightly charred.',
        'Slice the avocados and prep the toppings.',
        'Assemble the tacos and serve with lime wedges.',
      ],
      sourceUrl: undefined,
      createdBy: 'u2',
      createdAt: daysAgoIso(6),
      updatedAt: daysAgoIso(6),
    },
    {
      id: 'r6',
      householdId: 'h1',
      title: 'Honey Garlic Salmon',
      description: 'Pan-seared salmon glazed in a sweet, savory honey garlic sauce with roasted vegetables.',
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      tags: ['seafood', 'healthy', 'dinner', 'high-protein'],
      ingredients: [
        { id: createId('ing'), quantity: 4, unit: '', name: 'salmon fillets' },
        { id: createId('ing'), quantity: 3, unit: 'tbsp', name: 'honey' },
        { id: createId('ing'), quantity: 3, unit: 'cloves', name: 'garlic' },
        { id: createId('ing'), quantity: 2, unit: 'tbsp', name: 'soy sauce' },
        { id: createId('ing'), quantity: 1, unit: 'lb', name: 'broccoli florets' },
      ],
      instructions: [
        'Roast the vegetables until tender.',
        'Whisk together honey, garlic, and soy sauce.',
        'Sear the salmon until golden.',
        'Add the glaze and spoon it over the salmon until glossy.',
        'Serve with the roasted vegetables.',
      ],
      sourceUrl: undefined,
      createdBy: 'u1',
      createdAt: daysAgoIso(4),
      updatedAt: daysAgoIso(4),
    },
  ]

  const mealAssignments = [
    { id: createId('slot'), householdId: 'h1', date: weekDates[0], mealType: 'breakfast', recipeId: 'r4', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[0], mealType: 'dinner', recipeId: 'r1', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[1], mealType: 'dinner', recipeId: 'r2', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[2], mealType: 'breakfast', recipeId: 'r4', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[2], mealType: 'dinner', recipeId: 'r3', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[3], mealType: 'dinner', recipeId: 'r6', notes: '' },
    { id: createId('slot'), householdId: 'h1', date: weekDates[4], mealType: 'dinner', recipeId: 'r5', notes: '' },
  ]

  const shoppingItems = [
    {
      id: 'si1',
      householdId: 'h1',
      name: 'Romaine lettuce',
      quantity: 2,
      unit: 'heads',
      category: 'produce',
      checked: false,
      sourceRecipeId: 'r1',
      sourceRecipeName: 'Grilled Chicken Caesar Salad',
      addedBy: 'u1',
      addedAt: daysAgoIso(2),
      syncStatus: 'synced',
    },
    {
      id: 'si2',
      householdId: 'h1',
      name: 'Greek yogurt',
      quantity: 2,
      unit: 'cups',
      category: 'dairy',
      checked: false,
      sourceRecipeId: 'r4',
      sourceRecipeName: 'Overnight Oats with Berries',
      addedBy: 'u3',
      addedAt: daysAgoIso(2),
      syncStatus: 'synced',
    },
    {
      id: 'si3',
      householdId: 'h1',
      name: 'Chicken thighs',
      quantity: 1.5,
      unit: 'lbs',
      category: 'meat',
      checked: true,
      sourceRecipeId: 'r3',
      sourceRecipeName: 'Thai Green Curry',
      addedBy: 'u1',
      addedAt: daysAgoIso(2),
      syncStatus: 'synced',
    },
    {
      id: 'si4',
      householdId: 'h1',
      name: 'Coconut milk',
      quantity: 2,
      unit: 'cans',
      category: 'pantry',
      checked: false,
      sourceRecipeId: 'r3',
      sourceRecipeName: 'Thai Green Curry',
      addedBy: 'u1',
      addedAt: daysAgoIso(1),
      syncStatus: 'synced',
    },
    {
      id: 'si5',
      householdId: 'h1',
      name: 'Corn tortillas',
      quantity: 1,
      unit: 'pack',
      category: 'bakery',
      checked: false,
      sourceRecipeId: 'r5',
      sourceRecipeName: 'Black Bean Tacos',
      addedBy: 'u2',
      addedAt: daysAgoIso(1),
      syncStatus: 'synced',
    },
    {
      id: 'si6',
      householdId: 'h1',
      name: 'Paper towels',
      quantity: 2,
      unit: 'rolls',
      category: 'household',
      checked: false,
      addedBy: 'u2',
      addedAt: daysAgoIso(1),
      syncStatus: 'synced',
    },
  ]

  const pantryItems = [
    {
      id: createId('pantry'),
      householdId: 'h1',
      name: 'olive oil',
      quantity: 1,
      unit: 'bottle',
      category: 'pantry',
      lowStockThreshold: 1,
      updatedAt: daysAgoIso(1),
    },
    {
      id: createId('pantry'),
      householdId: 'h1',
      name: 'eggs',
      quantity: 4,
      unit: '',
      category: 'dairy',
      lowStockThreshold: 6,
      updatedAt: daysAgoIso(1),
    },
    {
      id: createId('pantry'),
      householdId: 'h1',
      name: 'soy sauce',
      quantity: 0.5,
      unit: 'bottle',
      category: 'pantry',
      lowStockThreshold: 1,
      updatedAt: daysAgoIso(2),
    },
  ]

  return {
    users,
    households,
    householdMembers,
    invites,
    householdPreferences,
    recipes,
    mealAssignments,
    shoppingItems,
    pantryItems,
    sessions: [],
    meta: {
      seededAt: nowIso(),
    },
  }
}
